# Generated by Django 6.0.4 on 2026-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('guia_ejecucion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ejercicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rutinas',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rutinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RutinasEjercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_ejecucion', models.IntegerField()),
            ],
            options={
                'db_table': 'rutinas_ejercicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosEjerciciosFavoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuarios_ejercicios_favoritos',
                'managed': False,
            },
        ),
    ]
