# Generated by Django 6.0.4 on 2026-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionesIa',
            fields=[
                ('id_recomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.TextField()),
                ('tipo_alerta', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'recomendaciones_ia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrosProgreso',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tiempo_carrera_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('marca_personal_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'registros_progreso',
                'managed': False,
            },
        ),
    ]
