# Generated by Django 6.0.4 on 2026-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id_alimento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('calorias_por_gramo', models.DecimalField(decimal_places=4, max_digits=6)),
                ('proteinas_por_gramo', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
            options={
                'db_table': 'alimentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrosNutricion',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad_gramos', models.DecimalField(decimal_places=2, max_digits=7)),
                ('calorias_calculadas', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('proteinas_calculadas', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'registros_nutricion',
                'managed': False,
            },
        ),
    ]
