# Generated by Django 6.0.4 on 2026-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('genero', models.CharField(blank=True, max_length=9, null=True)),
                ('frecuencia_entrenamiento', models.IntegerField(blank=True, null=True)),
                ('estado_suscripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('qr_acceso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
