# Generated by Django 6.0.4 on 2026-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenadores',
            fields=[
                ('id_entrenador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('verificado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrenadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gimnasios',
            fields=[
                ('id_gimnasio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gimnasios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MensajesChat',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('contenido', models.TextField()),
            ],
            options={
                'db_table': 'mensajes_chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'promociones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosGimnasios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuarios_gimnasios',
                'managed': False,
            },
        ),
    ]
